version: '2'
services:
  cdaelocetestjhipster-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/cdaelocetestjhipster/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cdaelocetestjhipster
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
